controllers:
  resource: ../src/Controller/
  type: attribute

app_response_signup:
  path: "/response/signup"

app_response_contact:
  path: "/response/contact"

app_response_checkout:
  path: "/response/checkout"

app_response_refund:
  path: "/response/refund"

app_response_forgottenPassword:
  path: "/response/forgottenPassword"
